apiVersion: 1

deleteDatasources:
    - name: Prometheus
    - name: Loki
    - name: Tempo

datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://localhost:9090
      access: proxy
      ordId: 1
      basicAuth: false
      isDefault: false
      version: 1
      editable: true
      jsonData:
          httpMethod: GET
    - name: Tempo
      type: tempo
      uid: tempo
      url: http://tempo:3100
      access: proxy
      ordId: 1
      basicAuth: false
      isDefault: false
      version: 1
      editable: true
      jsonData:
          httpMethod: GET
          serviceMap:
              datasourceUid: 'prometheus'
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      ordId: 1
      editable: true
      url: http://localhost:3100
      jsonData:
          httpHeaderName1: "X-Scope-OrgID"
      secureJsonData:
          httpHeaderValue1: "tenant1"