spring:
    application:
        name: "configserver"
    profiles:
        active: native
    cloud:
      config:
        server:
          native:
              search-locations: "file:///E:/ConfigFiles/config" # defining a path with config files anywhere in file system
#              search-locations: "classpath:/config" # defining a path with config files within Config Server

server:
    port: 8071