spring:
    config:
        activate:
            on-profile: "qa"

build:
    version: "2.0"

accounts:
    message: "Welcome to EazyBank accounts related QA APIs "
    contactDetails:
        name: "Utkarsh Mishra - QA Lead"
        email: "m.utkarsh@demobank.com"
    onCallSupport:
        - (666) 265-3765
        - (666) 734-8371