spring:
    config:
        activate:
            on-profile: "prod"

build:
    version: "1.0"

accounts:
    message: "Welcome to DemoBank accounts related Production APIs "
    contactDetails:
        name: "Utkarsh Mishra - Production Owner"
        email: "m.utkarsh@demobank.com"
    onCallSupport:
        - (453) 392-4829
        - (236) 203-0384