build:
    version: "1.0"

loans:
    message: "Welcome to DemoBank loans related prod APIs "
    contactDetails:
        name: "Utkarsh Mishra - Developer"
        email: "m.utkarsh@general.com"
    onCallSupport:
        - (+91) 1234-657-890
        - (+91) 9876-543-210